#Project Euler 11/18/20


##Can publicly post first 100 solutions

# Question 1
# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
# Find the sum of all the multiples of 3 or 5 below 1000.


sum_vect_mults_of_5_3 <- sum(which(1:999 %% 3 == 0 | 1:999 %% 5 == 0))


sum_vect_mults_of_5_3 # The Answer is 233,168

#-----------------------------------------------------------------------------

# Question 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#   
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


fibfunction <- function(){
#browser()
  fib <- as.vector(1)
  
  while(fib[length(fib)] <= 4000000L) {
    
  fib <-  append(fib, fib[length(fib)] + fib[max(1, length(fib) - 1)])
    
  }
  

sum(fib[fib %% 2 ==0])

}

fibfunction()

#The Answer is 4,613,732


fibfunction_NO_Int_Force <- function(){
  #browser()
  fib <- as.vector(1)
  
  while(fib[length(fib)] <= 4000000) {
    
    fib <-  append(fib, fib[length(fib)] + fib[max(1, length(fib) - 1)])
    
  }
  
  
  sum(fib[fib %% 2 ==0])
  
}



int <- microbenchmark::microbenchmark(fibfunction())
no_int <- microbenchmark::microbenchmark(fibfunction_NO_Int_Force())



hist(int$time, col = "blue")
hist(no_int$time, col = "red", add = TRUE)

#very curious, forcing int via "L" is slower on average, but more consistent.


#----------------------------------------------------------------------

# Question 3

# The prime factors of 13195 are 5, 7, 13 and 29.
# 
# What is the largest prime factor of the number 600851475143 ?


find_primes



factors <- which(13195 %% 1:13195 == 0)

findmults <- function(x){
  
  which(x %% 1:x == 0)
  
}

findmults(13195)





for (num in factors){
  #browser()
  for (element in 2:num - 1){
    if (num %% element == 0){
      break
    } else { return(num)}
  }
}



#new paradigm -USE ANY
factors <- which(13195 %% 1:13195 == 0)

primes <- NULL

for (number in which(factors > 1)) {
browser()
  if(any(number %% 2:(number - 1) == 0) == FALSE) {
    
    append(primes, number)
    
  }}
 
  





which(factors )



